# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-14 04:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20171214_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='/static/photo'),
        ),
    ]
