# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-14 07:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20171214_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar2',
            field=models.ImageField(blank=True, null=True, upload_to='static/photo'),
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar3',
            field=models.ImageField(blank=True, null=True, upload_to='static/photo'),
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar4',
            field=models.ImageField(blank=True, null=True, upload_to='static/photo'),
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar5',
            field=models.ImageField(blank=True, null=True, upload_to='static/photo'),
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar6',
            field=models.ImageField(blank=True, null=True, upload_to='static/photo'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='static/photo'),
        ),
    ]
