# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-15 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20171215_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='photo'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar2',
            field=models.ImageField(blank=True, null=True, upload_to='photo'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar3',
            field=models.ImageField(blank=True, null=True, upload_to='photo'),
        ),
    ]
