# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-22 02:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(max_length=10000),
        ),
    ]
