# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-23 06:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_works'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='works',
            name='work',
        ),
        migrations.AddField(
            model_name='works',
            name='bioa',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
