# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-23 07:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20171223_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='works',
            name='work',
            field=models.ImageField(blank=True, null=True, upload_to='photo'),
        ),
    ]
