# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-23 07:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_works_work'),
    ]

    operations = [
        migrations.RenameField(
            model_name='works',
            old_name='bioa',
            new_name='简介',
        ),
    ]
