# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-23 07:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_auto_20171223_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='works',
            name='标题',
            field=models.CharField(blank=True, max_length=70),
        ),
    ]
