# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-24 06:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_works_标题'),
    ]

    operations = [
        migrations.RenameField(
            model_name='works',
            old_name='简介',
            new_name='intorduce',
        ),
        migrations.RenameField(
            model_name='works',
            old_name='标题',
            new_name='titles',
        ),
    ]
