# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-28 08:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_auto_20171224_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='web_post', to='users.Category'),
        ),
        migrations.AlterField(
            model_name='works',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='web_work', to=settings.AUTH_USER_MODEL),
        ),
    ]
