# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-28 09:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_auto_20171228_1702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='avatar2',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='avatar3',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='works',
            name='tags',
        ),
        migrations.AddField(
            model_name='works',
            name='tags',
            field=models.ForeignKey(blank=True, default=123, on_delete=django.db.models.deletion.CASCADE, to='users.Tag'),
            preserve_default=False,
        ),
    ]
