# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-29 04:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_auto_20171229_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='web_comment', to=settings.AUTH_USER_MODEL),
        ),
    ]
