# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-01-04 10:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0042_auto_20171229_1224'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author',
            new_name='avatar',
        ),
    ]
