# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-01-04 11:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0045_comment_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', tinymce.models.HTMLField(verbose_name='文章详情')),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.Post', verbose_name='所属文章')),
            ],
        ),
    ]
