# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-01-04 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0046_articledetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='admin_Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('body', models.TextField()),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='articledetail',
            name='article',
        ),
        migrations.DeleteModel(
            name='ArticleDetail',
        ),
    ]
